change README
dragonfireclient/dragonfireclient pull request #52
Opened 2022-08-23 02:34 UTC by Pantyhose-X

Add dragonfireclient description

2022-09-24 22:51 UTC, corarona requested changes
Looks good but please copy the compiling/installation section back to readme

2022-09-24 22:51 UTC, corarona commented on Minetest.md
> +Compiling
This part has been changed to document the process for dragonfire. It should stay in readme.md

2022-09-24 22:52 UTC, corarona commented
This is where it was added: https://github.com/dragonfireclient/dragonfireclient/pull/35

2022-09-30 08:38 UTC, Pantyhose-X commented
Already changed, please merge it

2023-02-02 02:30 UTC, closed without merging